<a href="https://colab.research.google.com/github/RenzoAlvaroshan/Numpy-Tutorial/blob/master/NumPy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
arr = np.arange(0,11)

In [0]:
slice_of_arr = arr [0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [0]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy = arr.copy()

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
arr_2d[2][1]

40

In [0]:
arr_2d[2,2]

45

In [0]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
bool_array = arr > 5

In [0]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [0]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [0]:
arr[arr<3]

array([1, 2])

In [0]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
arr_2d[3,1:5]

array([31, 32, 33, 34])

In [0]:
arr_2d[4,6:]

array([46, 47, 48, 49])

In [0]:
arr_2d = np.arange(20).reshape(4,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])