<a href="https://colab.research.google.com/github/RenzoAlvaroshan/Numpy-Tutorial/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
my_list = [1,2,3]

In [0]:
arr = np.array(my_list)

In [0]:
arr

array([1, 2, 3])

In [0]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [0]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [0]:
np.random.randn(5)

array([-0.85046106,  0.0332918 , -1.4086862 ,  0.92371464,  0.27876129])

In [0]:
np.random.randint(1,10000,10)

array([6288, 4966, 6621,  555, 3724, 2836, 8695, 4703, 3734, 3442])

In [0]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 9, 15, 46, 13, 29, 48, 49, 37, 46,  1])

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
ranarr.argmax()

6

In [0]:
ranarr.argmin()

9

In [0]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
arr.shape

(5, 5)

In [0]:
arr.dtype

dtype('int64')

In [0]:
from numpy.random import randint
randint(2,10)

4